from enum import Enum


class MainViewState(int, Enum):
    MAIN_MENU = 0

    PLAYERS_MENU = 1
    NEW_PLAYER = 2
    EDIT_PLAYER_MENU = 3
    EDIT_PLAYER = 4

    TOURNAMENTS_MENU = 5

    NEW_TOURNAMENT = 6
    EDIT_TOURNAMENT_MENU = 7
    EDIT_TOURNAMENT = 8
    EDIT_ROUND_MENU = 9
    EDIT_ROUND = 10
    EDIT_MATCH_MENU = 11
    EDIT_MATCH = 12

    CONTINUE_TOURNAMENT_MENU = 13
    CONTINUE_TOURNAMENT = 14

    REPORTS_MENU = 15
    REPORTS_ALPHA_PLAYERS = 16
    REPORTS_RANK_PLAYERS = 17
    REPORTS_SCORE_PLAYERS = 18
    REPORTS_TOURNAMENTS_MENU = 19
    REPORTS_ROUNDS_MENU = 20
    REPORTS_MATCHS_MENU = 21

    CHOOSE_MATCH_WINNER = -9
    SET_MATCH_SCORE = -8
    EDIT_TOURNAMENT_STYLE = -7

    CONTINUE_FINISHED_TOURNAMENT = 22
    CONTINUE_STARTED_ROUND = 23
    CONTINUE_END_ROUND = 24
    CONTINUE_END_MATCH = 25
    CONTINUE_START_ROUND = 26
    CONTINUE_START_MATCH = 27
    CONTINUE_FINISHED_ROUND = 28
    CONTINUE_END_TOURNAMENT = 29
    CONTINUE_INIT_TOURNAMENT = 30

    SELECT_TOURNAMENT = 31
    SELECT_ROUND = 32
    SELECT_MATCH = 33
    SELECT_PLAYER = 34

    SAVE_ITEM = -6
    EDIT_FIELD = -5
    BACK = -4
    LOAD_DATABASE = -3
    SAVE_DATABASE = -2
    QUIT = -1
